import { useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Calendar } from "@/components/ui/calendar";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { format, addDays } from "date-fns";
import { es } from "date-fns/locale";
import { CalendarIcon, FileSearch, User, Briefcase, MapPin, Building, Loader2, Phone, Mail } from "lucide-react";
import { cn } from "@/lib/utils";

interface NuevoEstudioVerificadorDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  verificadorId: string;
  verificadorUserId: string;
  onSuccess?: () => void;
}

export function NuevoEstudioVerificadorDialog({
  open,
  onOpenChange,
  verificadorId,
  verificadorUserId,
  onSuccess,
}: NuevoEstudioVerificadorDialogProps) {
  const { toast } = useToast();
  const [loading, setLoading] = useState(false);
  const [nombreCandidato, setNombreCandidato] = useState("");
  const [clienteEmpresa, setClienteEmpresa] = useState("");
  const [puestoVacante, setPuestoVacante] = useState("");
  const [direccionVisita, setDireccionVisita] = useState("");
  const [telefonoCandidato, setTelefonoCandidato] = useState("");
  const [emailCandidato, setEmailCandidato] = useState("");
  const [fechaLimite, setFechaLimite] = useState<Date>(addDays(new Date(), 7));
  const [observaciones, setObservaciones] = useState("");

  const resetForm = () => {
    setNombreCandidato("");
    setClienteEmpresa("");
    setPuestoVacante("");
    setDireccionVisita("");
    setTelefonoCandidato("");
    setEmailCandidato("");
    setFechaLimite(addDays(new Date(), 7));
    setObservaciones("");
  };

  const handleSubmit = async () => {
    if (!nombreCandidato || !direccionVisita || !puestoVacante) {
      toast({
        title: "Campos requeridos",
        description: "Nombre del candidato, puesto y dirección son obligatorios",
        variant: "destructive",
      });
      return;
    }

    setLoading(true);
    try {
      // Use a generated UUID as placeholder candidato_user_id for direct studies
      const placeholderCandidatoId = crypto.randomUUID();

      const { data, error } = await supabase
        .from("estudios_socioeconomicos")
        .insert([{
          candidato_user_id: placeholderCandidatoId,
          solicitante_user_id: verificadorUserId,
          verificador_id: verificadorId,
          nombre_candidato: nombreCandidato,
          vacante_puesto: puestoVacante,
          direccion_visita: direccionVisita,
          fecha_limite: fechaLimite.toISOString(),
          estatus: "en_proceso",
          es_estudio_directo: true,
          cliente_empresa: clienteEmpresa || null,
          telefono_candidato: telefonoCandidato || null,
          email_candidato: emailCandidato || null,
          observaciones_finales: observaciones || null,
          folio: "", // Auto-generated by trigger
        }])
        .select()
        .single();

      if (error) throw error;

      toast({
        title: "✅ Estudio creado",
        description: `Estudio socioeconómico directo registrado (Folio: ${data?.folio || "generado"})`,
      });

      resetForm();
      onOpenChange(false);
      onSuccess?.();
    } catch (error: any) {
      console.error("Error creating study:", error);
      toast({
        title: "Error al crear estudio",
        description: error.message,
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-lg max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileSearch className="h-5 w-5 text-primary" />
            Nuevo Estudio Directo
          </DialogTitle>
          <DialogDescription>
            Registra un estudio socioeconómico para tu propio cliente
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-4">
          <div className="space-y-2">
            <Label className="flex items-center gap-2">
              <User className="h-4 w-4" />
              Nombre del Candidato *
            </Label>
            <Input
              value={nombreCandidato}
              onChange={(e) => setNombreCandidato(e.target.value)}
              placeholder="Nombre completo del candidato"
            />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label className="flex items-center gap-2">
                <Phone className="h-4 w-4" />
                Teléfono
              </Label>
              <Input
                value={telefonoCandidato}
                onChange={(e) => setTelefonoCandidato(e.target.value)}
                placeholder="Teléfono del candidato"
              />
            </div>
            <div className="space-y-2">
              <Label className="flex items-center gap-2">
                <Mail className="h-4 w-4" />
                Email
              </Label>
              <Input
                type="email"
                value={emailCandidato}
                onChange={(e) => setEmailCandidato(e.target.value)}
                placeholder="Email del candidato"
              />
            </div>
          </div>

          <div className="space-y-2">
            <Label className="flex items-center gap-2">
              <Building className="h-4 w-4" />
              Cliente / Empresa
            </Label>
            <Input
              value={clienteEmpresa}
              onChange={(e) => setClienteEmpresa(e.target.value)}
              placeholder="Nombre de la empresa o cliente"
            />
          </div>

          <div className="space-y-2">
            <Label className="flex items-center gap-2">
              <Briefcase className="h-4 w-4" />
              Puesto *
            </Label>
            <Input
              value={puestoVacante}
              onChange={(e) => setPuestoVacante(e.target.value)}
              placeholder="Puesto al que aspira el candidato"
            />
          </div>

          <div className="space-y-2">
            <Label className="flex items-center gap-2">
              <MapPin className="h-4 w-4" />
              Dirección de Visita *
            </Label>
            <Textarea
              value={direccionVisita}
              onChange={(e) => setDireccionVisita(e.target.value)}
              placeholder="Dirección completa para la visita domiciliaria"
              rows={2}
            />
          </div>

          <div className="space-y-2">
            <Label>Fecha Límite de Entrega *</Label>
            <Popover>
              <PopoverTrigger asChild>
                <Button
                  variant="outline"
                  className={cn(
                    "w-full justify-start text-left font-normal",
                    !fechaLimite && "text-muted-foreground"
                  )}
                >
                  <CalendarIcon className="mr-2 h-4 w-4" />
                  {fechaLimite ? format(fechaLimite, "PPP", { locale: es }) : "Selecciona fecha"}
                </Button>
              </PopoverTrigger>
              <PopoverContent className="w-auto p-0" align="start">
                <Calendar
                  mode="single"
                  selected={fechaLimite}
                  onSelect={(date) => date && setFechaLimite(date)}
                  disabled={(date) => date < new Date()}
                  initialFocus
                />
              </PopoverContent>
            </Popover>
          </div>

          <div className="space-y-2">
            <Label>Observaciones</Label>
            <Textarea
              value={observaciones}
              onChange={(e) => setObservaciones(e.target.value)}
              placeholder="Notas adicionales sobre el estudio..."
              rows={2}
            />
          </div>
        </div>

        <div className="flex justify-end gap-2 pt-4 border-t">
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Cancelar
          </Button>
          <Button onClick={handleSubmit} disabled={loading}>
            {loading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
            Crear Estudio Directo
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
